# Phonic AI Calling Agent - Development Configuration

app:
  name: "Phonic AI Calling Agent"
  version: "0.1.0-dev"
  environment: "dev"
  debug: true
  host: "0.0.0.0"
  port: 8080

database:
  host: "localhost"
  port: 5432
  username: "phonic"
  password: "phonic_dev_password"
  database: "phonic"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "1h"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10

moshi:
  stt:
    host: "localhost"
    port: 8001
    websocket_path: "/transcribe"
    timeout: "30s"
    retry_attempts: 3
    sample_rate: 16000
    channels: 1
    chunk_size: 1600
  tts:
    host: "localhost"
    port: 8002
    websocket_path: "/synthesize"
    timeout: "30s"
    retry_attempts: 3
    voice_id: "default"
    speed: 1.0
    quality: "high"

services:
  gateway:
    host: "localhost"
    port: 8080
    timeout: "30s"
  session:
    host: "localhost"
    port: 8083
    timeout: "30s"
  orchestrator:
    host: "localhost"
    port: 8084
    timeout: "30s"
  stt_client:
    host: "localhost"
    port: 8085
    timeout: "30s"
  tts_client:
    host: "localhost"
    port: 8086
    timeout: "30s"

logging:
  level: "debug"
  format: "json"
  output: "stdout"

security:
  jwt_secret: "dev-jwt-secret-key-change-in-production"
  jwt_expiry_hours: 24
  rate_limit:
    requests_per_minute: 1000
    burst_size: 500
    window_size: "1m"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
      - "http://127.0.0.1:3000"
      - "http://127.0.0.1:8080"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"

storage:
  endpoint: "localhost:9000"
  access_key: "phonic"
  secret_key: "phonic_dev_password"
  bucket: "phonic-audio-dev"
  region: "us-east-1"
  use_ssl: false
  audio_retention_days: 7  # Shorter retention for development
